config/routes.rb
Rails.application.routes.draw do

  resources :budget_items
  resources :projects, path: '/' do
    get  'budget/edit'
    get  'budget/view'
    post 'budget'
    get  'progress/view'
    get  'daily_submission'
    resources :headings
    resources :staffs
    resources :machines
  end

end

app/models/staff.rb
class Staff < ActiveRecord::Base

  belongs_to :project
  validates :first_name, :email, :project_id, presence: true

  def to_s
    "#{first_name} #{last_name}"
  end

end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController

  before_action :set_project
  before_action :set_staff, only: [:show, :edit, :update, :destroy]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = @project.staff
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)
    @staff.project = @project

    respond_to do |format|
      if @staff.save
        format.html { redirect_to [@project, @staff], notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to [@project, @staff], notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_project
      @project = Project.where(url: params[:project_id]).first
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:project_id, :first_name, :last_name, :email, :phone, :role)
    end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<div class="row">

  <!-- col-left -->
  <div class="col-sm-12 col-md-6">
    <div class="panel panel-default panel-hovered panel-stacked mb30">
      <div class="panel-heading"><%= @project.name %> Staff Member</div>
      <div class="panel-body">

        <%= form_for([@project, @staff]) do |f| %>
          <% if @staff.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

              <ul>
              <% @staff.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field">
            <%= f.label :first_name %><br>
            <%= f.text_field :first_name %>
          </div>
          <div class="field">
            <%= f.label :last_name %><br>
            <%= f.text_field :last_name %>
          </div>
          <div class="field">
            <%= f.label :email %><br>
            <%= f.text_field :email %>
          </div>
          <div class="field">
            <%= f.label :phone %><br>
            <%= f.text_field :phone %>
          </div>
          <div class="field">
            <%= f.label :role %><br>
            <%= f.text_field :role %>
          </div>
          <div class="actions">
            <%= f.submit %>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/staffs/edit.html.erb
<%= render '/projects/side_menu', project: @project %>
<%= content_for(:page_title, "Editing #{@project.name} Staff") %>

<%= render 'form' %>

<%= link_to 'Show', [@project, @staff] %> |
<%= link_to 'Back', project_staffs_path(@project) %>

app/views/staffs/index.html.erb
<%= render '/projects/side_menu', project: @project %>
<%= content_for(:page_title, "#{@project.name} Staff List") %>

<div class="col-sm-12 col-md-12">
  <div class="panel panel-lined table-responsive panel-hovered mb20 data-table">

    <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper no-footer">

      <table class="table table-bordered table-striped dataTable no-footer">
        <thead>
          <tr>
            <th>Project</th>
            <th>First name</th>
            <th>Last name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Role</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @staffs.each do |staff| %>
            <tr>
              <td><%= staff.project_id %></td>
              <td><%= staff.first_name %></td>
              <td><%= staff.last_name %></td>
              <td><%= staff.email %></td>
              <td><%= staff.phone %></td>
              <td><%= staff.role %></td>
              <td><%= link_to 'Show', [@project, staff] %></td>
              <td><%= link_to 'Edit', edit_project_staff_path(@project, staff) %></td>
              <td><%= link_to 'Destroy', [@project, staff], method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <div class="panel-body">
        <%= link_to '+ Add New Staff Member', new_project_staff_path(@project) %>
      </div>

    </div>
  </div>
</div>

app/views/staffs/new.html.erb
<%= render '/projects/side_menu', project: @project %>
<%= content_for(:page_title, "#{@project.name} Staff") %>

<%= render 'form' %>

app/views/staffs/show.html.erb
<%= render '/projects/side_menu', project: @project %>
<%= content_for(:page_title, "#{@staff}") %>

<div class="row">

  <div class="col-md-6">
    <div class="panel panel-default panel-stacked panel-hovered mb30">
      <div class="panel-heading">User Details</div>
      <div class="panel-body">
        <p id="notice"><%= notice %></p>

        <p>
          <strong>Email:</strong>
          <%= @staff.email %>
        </p>

        <p>
          <strong>Phone:</strong>
          <%= @staff.phone %>
        </p>

        <p>
          <strong>Role:</strong>
          <%= @staff.role %>
        </p>

        <%= link_to 'Edit', edit_project_staff_path(@project, @staff) %> |
        <%= link_to 'Back', project_staffs_path(@project) %>
      </div>
    </div>
  </div>

  <div class="col-md-6">
    <div class="panel panel-default panel-stacked panel-hovered mb30">
      <div class="panel-heading">Managing Headings:</div>
      <div class="panel-body">

      </div>
    </div>
  </div>
</div>