config/routes.rb
Rails.application.routes.draw do

  resources :budget_items
  resources :projects, path: '/' do
    get  'budget/edit'
    get  'budget/view'
    post 'budget'
    get  'progress/view'
    get  'daily_submission'
    resources :headings
    resources :staffs
    resources :machines
  end

end

app/models/budget_item.rb
class BudgetItem < ActiveRecord::Base
  belongs_to :project
  validates :date, uniqueness: { scope: :project_id }
  validates :date, presence: true

  def to_s
    "#{date.strftime('%b %Y')}"
  end

end

app/controllers/budget_items_controller.rb
class BudgetItemsController < ApplicationController
  before_action :set_budget_item, only: [:show, :edit, :update, :destroy]

  # GET /budget_items
  # GET /budget_items.json
  def index
    @budget_items = BudgetItem.all
  end

  # GET /budget_items/1
  # GET /budget_items/1.json
  def show
  end

  # GET /budget_items/new
  def new
    @budget_item = BudgetItem.new
  end

  # GET /budget_items/1/edit
  def edit
  end

  # POST /budget_items
  # POST /budget_items.json
  def create
    @budget_item = BudgetItem.new(budget_item_params)

    respond_to do |format|
      if @budget_item.save
        format.html { redirect_to @budget_item, notice: 'Budget item was successfully created.' }
        format.json { render :show, status: :created, location: @budget_item }
      else
        format.html { render :new }
        format.json { render json: @budget_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budget_items/1
  # PATCH/PUT /budget_items/1.json
  def update
    respond_to do |format|
      if @budget_item.update(budget_item_params)
        format.html { redirect_to @budget_item, notice: 'Budget item was successfully updated.' }
        format.json { render :show, status: :ok, location: @budget_item }
      else
        format.html { render :edit }
        format.json { render json: @budget_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budget_items/1
  # DELETE /budget_items/1.json
  def destroy
    @budget_item.destroy
    respond_to do |format|
      format.html { redirect_to budget_items_url, notice: 'Budget item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget_item
      @budget_item = BudgetItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def budget_item_params
      params.require(:budget_item).permit(:date, :project_id, :development_metres, :rehab_metres)
    end
end

app/helpers/budget_items_helper.rb
module BudgetItemsHelper
end

app/views/budget_items/_form.html.erb
<%= form_for(@budget_item) do |f| %>
  <% if @budget_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@budget_item.errors.count, "error") %> prohibited this budget_item from being saved:</h2>

      <ul>
      <% @budget_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.number_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :development_metres %><br>
    <%= f.number_field :development_metres %>
  </div>
  <div class="field">
    <%= f.label :rehab_metres %><br>
    <%= f.number_field :rehab_metres %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/budget_items/edit.html.erb
<h1>Editing Budget Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @budget_item %> |
<%= link_to 'Back', budget_items_path %>

app/views/budget_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Budget Items</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Project</th>
      <th>Development metres</th>
      <th>Rehab metres</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @budget_items.each do |budget_item| %>
      <tr>
        <td><%= budget_item.date %></td>
        <td><%= budget_item.project_id %></td>
        <td><%= budget_item.development_metres %></td>
        <td><%= budget_item.rehab_metres %></td>
        <td><%= link_to 'Show', budget_item %></td>
        <td><%= link_to 'Edit', edit_budget_item_path(budget_item) %></td>
        <td><%= link_to 'Destroy', budget_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Budget item', new_budget_item_path %>

app/views/budget_items/new.html.erb
<h1>New Budget Item</h1>

<%= render 'form' %>

<%= link_to 'Back', budget_items_path %>

app/views/budget_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @budget_item.date %>
</p>

<p>
  <strong>Project:</strong>
  <%= @budget_item.project_id %>
</p>

<p>
  <strong>Development metres:</strong>
  <%= @budget_item.development_metres %>
</p>

<p>
  <strong>Rehab metres:</strong>
  <%= @budget_item.rehab_metres %>
</p>

<%= link_to 'Edit', edit_budget_item_path(@budget_item) %> |
<%= link_to 'Back', budget_items_path %>