config/routes.rb
Rails.application.routes.draw do

  resources :budget_items
  resources :projects, path: '/' do
    get  'budget/edit'
    get  'budget/view'
    post 'budget'
    get  'progress/view'
    get  'daily_submission'
    resources :headings
    resources :staffs
    resources :machines
  end

end

app/controllers/budget_controller.rb
class BudgetController < ApplicationController

  before_action :set_project

  def index

  end

  def edit

  end

  def update

  end

  private

    def set_project
      @project = Project.where(url: params[:project_id]).first
    end

end

app/views/budget/edit.html.erb
<%= render '/projects/side_menu', project: @project %>
<%= content_for(:page_title, "Editing #{@project.name} Budget") %>

<div class="col-sm-12 col-md-12">
  <div class="panel panel-lined table-responsive panel-hovered mb20 data-table">

    <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper no-footer">

      <%= simple_form_for(:budget, url: project_budget_path(@project), class: 'form-horizontal') do |f| %>
        <table class="table table-bordered table-striped dataTable no-footer">
          <thead>
            <tr>
              <th>Date</th>
              <th>Development Meters</th>
              <th>Rehab Meters</th>
            </tr>
          </thead>
          <tbody>
          <% @project.sorted_budget_items.each do |budget_item| %>
            <tr>
              <td><%= budget_item %></td>
              <td><input name="budget_item[<%= budget_item.id %>][development_metres]" type='text' value='<%= budget_item.development_metres %>' /></td>
              <td><input name="budget_item[<%= budget_item.id %>][rehab_metres]" type='text' value='<%= budget_item.rehab_metres %>' /></td>
            </tr>
          <% end %>
          </tbody>
        </table>

        <%= f.button :submit %>

      <% end %>

      <br />
      <%= link_to '<< Back', project_path(@project) %>

    </div>

  </div>
</div>

app/views/budget/view.html.erb
<%= content_for :page_title, 'Budget Insight' %>
<%= render '/projects/side_menu', project: @project %>

<!-- Year Completed:  45 of 365 days (13%)
Metres Completed 2344/22,000 (10%)
Current target 2712 (14% behind target)

 -->

<div class="row">
  <div class="col-md-12 col-sm-12">
    <div class="panel-body">
      <h4>Yearly Overview</h4>
    </div>
  </div>
</div>


<div class="row">
  <div class="col-md-4 col-sm-6">
    <div class="panel panel-default mb20 mini-box panel-hovered">
      <div class="panel-body">
        <div class="clearfix">
          <div class="info left">
            <h4 class="mt0 text-primary text-bold">45 of 365 days (13%)</h4>
            <h5 class="text-light mb0">Year Completed</h5>
          </div>
          <div class="right ion ion-ios-pulse icon"></div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-4 col-sm-6">
    <div class="panel panel-default mb20 mini-box panel-hovered">
      <div class="panel-body">
        <div class="clearfix">
          <div class="info left">
            <h4 class="mt0 text-success text-bold">2,344m / 22,000m (10%)</h4>
            <h5 class="text-light mb0">Metres Completed</h5>
          </div>
          <div class="right ion ion-ios-pulse icon"></div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-4 col-sm-6">
    <div class="panel panel-default mb20 mini-box panel-hovered">
      <div class="panel-body">
        <div class="clearfix">
          <div class="info left">
            <h4 class="mt0 text-info text-bold">2,712m (14% behind target)</h4>
            <h5 class="text-light mb0">Current Target</h5>
          </div>
          <div class="right ion ion-alert-circled icon"></div>
        </div>
      </div>
    </div>
  </div>

  <!-- #end mini boxes -->
</div> <!-- #end row -->

<div class="row">
  <div class="col-md-12 col-sm-12">
    <div class="panel-body">
      <h4>MOP Performance - Current Month</h4>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-4 col-sm-6">
    <div class="panel panel-default mb20 mini-box panel-hovered">
      <div class="panel-body">
        <div class="clearfix">
          <div class="info left">
            <h4 class="mt0 text-primary text-bold">15 of 31 days (45%)</h4>
            <h5 class="text-light mb0">Current Month</h5>
          </div>
          <div class="right ion ion-ios-pulse icon"></div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-4 col-sm-6">
    <div class="panel panel-default mb20 mini-box panel-hovered">
      <div class="panel-body">
        <div class="clearfix">
          <div class="info left">
            <h4 class="mt0 text-success text-bold">900m / 2,015m (44%)</h4>
            <h5 class="text-light mb0">Metres Completed</h5>
          </div>
          <div class="right ion ion-ios-pulse icon"></div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-4 col-sm-6">
    <div class="panel panel-default mb20 mini-box panel-hovered">
      <div class="panel-body">
        <div class="clearfix">
          <div class="info left">
            <h4 class="mt0 text-info text-bold">900m / 975m (8% Behind target)</h4>
            <h5 class="text-light mb0">Current Target</h5>
          </div>
          <div class="right ion ion-alert-circled icon"></div>
        </div>
      </div>
    </div>
  </div>

  <!-- #end mini boxes -->
</div>


<div class="row">
  <div class="col-md-12 col-sm-12">
    <div class="panel-body">
      <h4>8 Day Performance</h4>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-4 col-sm-6">
    <div class="panel panel-default mb20 mini-box panel-hovered">
      <div class="panel-body">
        <div class="clearfix">
          <div class="info left">
            <h4 class="mt0 text-primary text-bold">3 of 7 days (43%)</h4>
            <h5 class="text-light mb0">Current Week</h5>
          </div>
          <div class="right ion ion-ios-pulse icon"></div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-4 col-sm-6">
    <div class="panel panel-default mb20 mini-box panel-hovered">
      <div class="panel-body">
        <div class="clearfix">
          <div class="info left">
            <h4 class="mt0 text-success text-bold">192m / 415m (44%)</h4>
            <h5 class="text-light mb0">Metres Completed</h5>
          </div>
          <div class="right ion ion-ios-pulse icon"></div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-4 col-sm-6">
    <div class="panel panel-default mb20 mini-box panel-hovered">
      <div class="panel-body">
        <div class="clearfix">
          <div class="info left">
            <h4 class="mt0 text-info text-bold">192m / 195m (2% Behind target)</h4>
            <h5 class="text-light mb0">Current Target</h5>
          </div>
          <div class="right ion ion-ios-pulse icon"></div>
        </div>
      </div>
    </div>
  </div>

  <!-- #end mini boxes -->
</div>



<div class="row">
  <div class="col-md-12 col-sm-12">
    <div class="panel-body">
      <h4>Daily Performance</h4>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-4 col-sm-6">
    <div class="panel panel-default mb20 mini-box panel-hovered">
      <div class="panel-body">
        <div class="clearfix">
          <div class="info left">
            <h4 class="mt0 text-primary text-bold">18 of 22 hours (82%)</h4>
            <h5 class="text-light mb0">Current Day</h5>
          </div>
          <div class="right ion ion-ios-pulse icon"></div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-4 col-sm-6">
    <div class="panel panel-default mb20 mini-box panel-hovered">
      <div class="panel-body">
        <div class="clearfix">
          <div class="info left">
            <h4 class="mt0 text-success text-bold">34m / 68m (41%)</h4>
            <h5 class="text-light mb0">Metres Completed</h5>
          </div>
          <div class="right ion ion-ios-pulse icon"></div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-4 col-sm-6">
    <div class="panel panel-default mb20 mini-box panel-hovered">
      <div class="panel-body">
        <div class="clearfix">
          <div class="info left">
            <h4 class="mt0 text-info text-bold">34m / 48.5m (20% behind)</h4>
            <h5 class="text-light mb0">Current Target</h5>
          </div>
          <div class="right ion ion-alert-circled icon"></div>
        </div>
      </div>
    </div>
  </div>

  <!-- #end mini boxes -->
</div>