config/routes.rb
Rails.application.routes.draw do

  resources :budget_items
  resources :projects, path: '/' do
    get  'budget/edit'
    get  'budget/view'
    post 'budget'
    get  'progress/view'
    get  'daily_submission'
    resources :headings
    resources :staffs
    resources :machines
  end

end

app/models/project.rb
class Project < ActiveRecord::Base

  paginates_per 10

  acts_as_url :name

  validates :name, presence: true, uniqueness: :true

  has_many :budget_items
  has_many :daily_summaries
  has_many :headings
  has_many :staff
  has_many :machines

  def to_param
    url
  end

  def sorted_budget_items
    create_missing_budget_items
  end

  def sorted_progress_data
    daily_summaries.sort_by(&:date)
  end

  def latest_summaries
    daily_summaries.order('date DESC').limit(8)
  end

  def behind_target?
    budget_status < 100
  end

  def available_machines
    machines.where('status != ?', 'Out of Action')
  end

  private

    def create_missing_budget_items
      count = 0
      results = []
      ((Date.today-1.month)..(Date.today+24.months)).select { |d| d.day == 1 }.collect do |date|
        if date.month == 7 && count > 2
          break
        else
          count += 1
          results << BudgetItem.where(project_id: id, date: date).first_or_create
        end
      end
      results.sort_by(&:date)
    end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.order(:name).where(owner: 'BHP').page params[:page]
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def budget
    budget_params.each do |id, vals|
      BudgetItem.find(id).update_attributes(vals)
    end
    flash[:notice] = 'Budget Saved'
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.where(url: params[:id]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :lat, :lng, :owner, :description)
    end

    def budget_params
      # FIXME: security issue here
      params.require(:budget_item).permit!
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_achievement_stats.html.erb
<div class="row">
  <div class="col-md-3 col-sm-6">
    <div class="panel panel-default mb20 mini-box panel-hovered">
      <div class="panel-body">
        <div class="clearfix">
          <div class="info left">
            <h4 class="mt0 text-primary text-bold">127m</h4>
            <h5 class="text-light mb0">Development Yesterday</h5>
          </div>
          <div class="right ion ion-ios-pulse icon"></div>
        </div>
      </div>
      <div class="panel-footer clearfix panel-footer-sm panel-footer-primary">
        <p class="mt0 mb0 left">% change</p>
        <span class="sparkline right" data-Type="bar" data-BarColor="#fff" data-Width="1.15em" data-Height="1.15em">10,8,9,3,5,8,5</span>
      </div>
    </div>
  </div>

  <div class="col-md-3 col-sm-6">
    <div class="panel panel-default mb20 mini-box panel-hovered">
      <div class="panel-body">
        <div class="clearfix">
          <div class="info left">
            <h4 class="mt0 text-success text-bold">132m</h4>
            <h5 class="text-light mb0">Rehab Yesterday</h5>
          </div>
          <div class="right ion ion-ios-pulse icon"></div>
        </div>
      </div>
      <div class="panel-footer clearfix panel-footer-sm panel-footer-success">
        <p class="mt0 mb0 left">% change</p>
        <span class="right sparkline" data-Type="bar" data-BarColor="#fff" data-Width="1.15em" data-Height="1.15em">3,5,9,8,6,10</span>
      </div>
    </div>
  </div>

  <div class="col-md-3 col-sm-6">
    <div class="panel panel-default mb20 mini-box panel-hovered">
      <div class="panel-body">
        <div class="clearfix">
          <div class="info left">
            <h4 class="mt0 text-info text-bold">110</h4>
            <h5 class="text-light mb0">Active Headings</h5>
          </div>
          <div class="right ion ion-ios-pulse icon"></div>
        </div>
      </div>
      <div class="panel-footer clearfix panel-footer-sm panel-footer-info">
        <p class="mt0 mb0 left">% change</p>
        <span class="right sparkline" data-Type="bar" data-BarColor="#fff" data-Width="1.15em" data-Height="1.15em">5,9,9,8,6,6</span>
      </div>
    </div>
  </div>

  <div class="col-md-3 col-sm-6">
    <div class="panel panel-default mb20 mini-box panel-hovered">
      <div class="panel-body">
        <div class="clearfix">
          <div class="info left">
            <h4 class="mt0 text-pink text-bold">80%</h4>
            <h5 class="text-light mb0">Heading Reports Submitted</h5>
          </div>
          <div class="right ion ion-ios-list-outline icon"></div>
        </div>
      </div>
      <div class="panel-footer clearfix panel-footer-sm panel-footer-pink">
        <p class="mt0 mb0 left">% change</p>
        <span class="sparkline right" data-Type="bar" data-BarColor="#fff" data-Width="1.15em" data-Height="1.15em">6,4,9,10,6,2</span>
      </div>
    </div>
  </div>
  <!-- #end mini boxes -->
</div> <!-- #end row -->

app/views/projects/_achievement_stats_individual.html.erb
<div class="row">
  <div class="col-md-3 col-sm-6">
    <div class="panel panel-default mb20 mini-box panel-hovered">
      <div class="panel-body">
        <div class="clearfix">
          <div class="info left">
            <h4 class="mt0 text-primary text-bold">
              <%= latest_summaries.present? ? "#{latest_summaries.first.actual_advance_metres}m" : 'None' %>
            </h4>
            <h5 class="text-light mb0">Development Yesterday</h5>
          </div>
          <div class="right ion ion-ios-pulse icon"></div>
        </div>
      </div>
      <div class="panel-footer clearfix panel-footer-sm panel-footer-primary">
        <p class="mt0 mb0 left">% change</p>
        <span class="sparkline right" data-Type="bar" data-BarColor="#fff" data-Width="1.15em" data-Height="1.15em">10,8,9,3,5,8,5</span>
      </div>
    </div>
  </div>

  <div class="col-md-3 col-sm-6">
    <div class="panel panel-default mb20 mini-box panel-hovered">
      <div class="panel-body">
        <div class="clearfix">
          <div class="info left">
            <h4 class="mt0 text-success text-bold">
              <%= latest_summaries.present? ? "#{latest_summaries.first.actual_rehab_metres}m" : 'None' %>
            </h4>
            <h5 class="text-light mb0">Rehab Yesterday</h5>
          </div>
          <div class="right ion ion-ios-pulse icon"></div>
        </div>
      </div>
      <div class="panel-footer clearfix panel-footer-sm panel-footer-success">
        <p class="mt0 mb0 left">% change</p>
        <span class="right sparkline" data-Type="bar" data-BarColor="#fff" data-Width="1.15em" data-Height="1.15em">
          <%= latest_summaries.present? ? latest_summaries.map(&:actual_rehab_metres).join(',') : '1,2,3,2,4,6' %>
        </span>
      </div>
    </div>
  </div>

  <div class="col-md-3 col-sm-6">
    <div class="panel panel-default mb20 mini-box panel-hovered">
      <div class="panel-body">
        <div class="clearfix">
          <div class="info left">
            <h4 class="mt0 text-info text-bold">
              <%= latest_summaries.present? ? "#{latest_summaries.first.actual_available_headings}" : 'None' %>
            </h4>
            <h5 class="text-light mb0">Active Headings Yesterday</h5>
          </div>
          <div class="right ion ion-ios-pulse icon"></div>
        </div>
      </div>
      <div class="panel-footer clearfix panel-footer-sm panel-footer-info">
        <p class="mt0 mb0 left">% change</p>
        <span class="right sparkline" data-Type="bar" data-BarColor="#fff" data-Width="1.15em" data-Height="1.15em">5,9,9,8,6,6</span>
      </div>
    </div>
  </div>

  <div class="col-md-3 col-sm-6">
    <div class="panel panel-default mb20 mini-box panel-hovered">
      <div class="panel-body">
        <div class="clearfix">
          <div class="info left">
            <h4 class="mt0 text-<%= @project.behind_target? ? 'pink' : 'success' %> text-bold">
              <% if @project.behind_target? %>
                <%= 100 - @project.budget_status %>% Behind Budget Target
              <% else %>
                <%= @project.budget_status - 100 %>% Ahead of Budget Target
              <% end %>
            </h4>
            <h5 class="text-light mb0">Monthly MOP Target</h5>
          </div>
          <div class="right ion ion-ios-list-outline icon"></div>
        </div>
      </div>
      <div class="panel-footer clearfix panel-footer-sm panel-footer-<%= @project.behind_target? ? 'pink' : 'success' %>">
        <p class="mt0 mb0 left">% change</p>
        <span class="sparkline right" data-Type="bar" data-BarColor="#fff" data-Width="1.15em" data-Height="1.15em">6,4,9,10,6,2</span>
      </div>
    </div>
  </div>
  <!-- #end mini boxes -->
</div> <!-- #end row -->

app/views/projects/_form.html.erb
<div class="row">

  <!-- col-left -->
  <div class="col-sm-12 col-md-6">
    <div class="panel panel-default panel-hovered panel-stacked mb30">
      <div class="panel-heading"><%= @project.name %></div>
      <div class="panel-body">

        <%= form_for(@project, class: 'form-horizontal') do |f| %>
          <% if @project.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

              <ul>
              <% @project.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field">
            <%= f.label :name %><br>
            <%= f.text_field :name %>
          </div>
          <div class="field">
            <%= f.label :owner %><br>
            <%= f.text_field :owner %>
          </div>
          <div class="field">
            <%= f.label :lat %><br>
            <%= f.text_field :lat %>
          </div>
          <div class="field">
            <%= f.label :lng %><br>
            <%= f.text_field :lng %>
          </div>
          <div class="field">
            <%= f.label :description %><br>
            <%= f.text_field :description %>
          </div>
          <div class="actions">
            <%= f.submit %>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/projects/_monthy_chart.html.erb
<div class="col-md-7">
  <div class="panel panel-default mb20 panel-hovered analytics">
    <div class="panel-heading">Analytics</div>
    <div class="panel-body">
      <%= link_to '/graph1-may05.png', :data => { :colorbox => true } do %>
        <img src='/graph1-may05.png' style='width:100%' />
      <% end %>
    </div>
  </div>

</div>

<script>
  // c3 chart

  $(document).ready(function() {
    var analyticsconfig = {
      bindto: "#c3chartAnalytics",
      data: {
        x: 'x',
        xFormat: '%Y%m%d',
        columns: [
          ['x',                     30, 100,  80, 140, 150, 200],
          ['actual_advance_metres', 90, 100, 170, 140, 190, 50],
          ['daily_advance_metres',  12,  22,  23,  14, 135, 26]
        ],
        type: 'spline',
        types: {
          'actual_advance_metres': 'bar',
          'daily_advance_metres':  'line'
        }
      },
      color: {
        pattern: ["#3F51B5",  "#38B4EE", "#4CAF50", "#E91E63"]
      },
      legend: {
        position: "inset"
      },
      size: {
        height: 330
      }
    };

    c3.generate(analyticsconfig);

  });
</script>

app/views/projects/_side_menu.html.erb
<% content_for(:side_menu) do %>
  <li>
    <%= link_to(project_path(project)) do %>
      <i class="ion ion-pinpoint"></i>
      <span class="text"><%= project.name %></span>
    <% end %>
  </li>

  <li>
    <%= link_to(edit_project_path(project)) do %>
      <i class="ion ion-edit"></i>
      <span class="text">Edit Project</span>
    <% end %>
  </li>

  <li>
    <%= link_to(project_budget_view_path(project)) do %>
      <i class="ion ion-social-usd"></i>
      <span class="text">Budget</span>
    <% end %>
  </li>

  <li>
    <%= link_to(project_progress_view_path(project)) do %>
      <i class="ion ion-stats-bars"></i>
      <span class="text">Progress Data</span>
    <% end %>
  </li>

  <li>
    <%= link_to(project_headings_path(project)) do %>
      <i class="ion ion-map"></i>
      <span class="text">Headings</span>
    <% end %>
  </li>

  <li>
    <%= link_to(project_staffs_path(project)) do %>
      <i class="ion ion-person-stalker"></i>
      <span class="text">Staff</span>
    <% end %>
  </li>

  <li>
    <%= link_to(project_machines_path(project)) do %>
      <i class="ion ion-settings"></i>
      <span class="text">Machinery</span>
    <% end %>
  </li>

  <li>
    <%= link_to(project_daily_submission_path(project)) do %>
      <i class="ion ion-arrow-graph-up-right"></i>
      <span class="text">Daily Submissions</span>
    <% end %>
  </li>

<% end %>

<!--
<li>
  <a href="calendar.html">
    <i class="ion ion-calendar"></i>
    <span class="text">Calendar</span>
    <span class="badge badge-xs badge-danger">hot</span>
  </a>
</li>
<li>
  <a href="material.html">
    <i class="ion ion-icecream"></i>
    <span class="text">Material</span>
    <span class="badge badge-xs badge-success">new</span>
  </a>
</li>

<li>
  <a href="javascript:;">
    <i class="ion ion-android-options"></i>
    <span class="text">UI Kit</span>
    <i class="arrow ion-chevron-left"></i>
    <span class="badge badge-xs badge-info">10</span>
  </a>
  <ul class="inner-drop list-unstyled">
    <li><a href="ui.buttons.html">Buttons</a></li>
    <li><a href="ui.typography.html">Typography</a></li>
    <li><a href="ui.grids.html">Grids</a></li>
    <li><a href="ui.panels.html">Panels</a></li>
    <li><a href="ui.notifications.html">Notifications</a></li>
    <li><a href="ui.tabs.html">Tabs &amp; Accordion</a></li>
    <li><a href="ui.progress-bars.html">Progress Bars</a></li>
    <li><a href="ui.extras.html">Extras</a></li>
  </ul>
</li>

<li>
  <a href="javascript:;">
    <i class="ion ion-asterisk"></i>
    <span class="text">Icons</span>
    <i class="arrow ion-chevron-left"></i>
    <span class="badge badge-xs badge-primary">2</span>
  </a>
  <ul class="inner-drop nested list-unstyled">
    <li><a href="icons.html">Font Awesome</a></li>
  </ul>
</li>

<li>
  <a href="javascript:;">
    <i class="ion ion-stats-bars"></i>
    <span class="text">Charts</span>
    <i class="arrow ion-chevron-left"></i>
  </a>
  <ul class="inner-drop list-unstyled">
    <li><a href="charts.c3.html">C3</a></li>
    <li><a href="charts.sparklines.html">Sparklines</a></li>
  </ul>
</li>
<li>
  <a href="javascript:;">
    <i class="ion ion-document-text"></i>
    <span class="text">Forms</span>
    <i class="arrow ion-chevron-left"></i>
  </a>
  <ul class="inner-drop list-unstyled">
    <li><a href="forms.elements.html">Elements</a></li>
  </ul>
</li>

<li>
  <a href="tables.html">
    <i class="ion ion-clipboard"></i>
    <span class="text">Tables</span>
  </a>
</li> -->

app/views/projects/daily_submission.html.erb
<%= content_for(:page_title, 'Daily Heading Progress Submission') %>

<% 1.upto(6).each do |i| %>
<div class="col-md-4 col-sm-6">
  <div class="panel panel-default panel-hovered panel-stacked mb30">
    <div class="panel-heading">Heading <%= i %></div>
    <div class="panel-body">
      <form role="form" class="form-horizontal" action="javascript:;"> <!-- form horizontal acts as a row -->
        <!-- with hint -->
        <div class="form-group">
          <label class="col-md-3 control-label">Advance</label>
          <div class="col-md-9">
            <input type="text" class="form-control" placeholder="eg 2.1">
          </div>
        </div>

        <!-- with hint -->
        <div class="form-group">
          <label class="col-md-3 control-label">Rehab</label>
          <div class="col-md-9">
            <input type="text" class="form-control" placeholder="eg 2.1">
          </div>
        </div>

        <div class="form-group">
          <label class="control-label small">Current Heading Status</label>
          <select id="status_<%= i %>" style="width: 100%" data-placeholder="Select a status">
            <% Heading::DefaultStatusTypes.each do |val| %>
              <option value='<%= val %>'><%= val %></option>
            <% end %>
          </select>
        </div>

        <script>
          $(document).ready(function(){
            $("#status_<%= i %>").select2();
          });
        </script>

      </form>
    </div>
  </div>
</div>
<% end %>

<div class="col-sm-12 col-md-12">
  <div class="panel panel-lined table-responsive panel-hovered mb20 data-table">
    <div class="panel-body">    <div class="clearfix right">
      <button class="btn btn-primary mr5 waves-effect" type="submit">Submit</button>
      <button class="btn btn-default waves-effect">Cancel</button>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<%= content_for(:page_title, 'Editing Project') %>
<%= render '/projects/side_menu', project: @project %>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<%= render 'achievement_stats' %>
<%= content_for :page_title, 'BHP Mining Projects' %>

<div class="row">
  <% @projects.each do |project| %>
    <div class="col-md-6">
      <div class="panel panel-default panel-stacked panel-hovered mb30">
        <div class="panel-heading">
          <%= link_to project.name, project %>
          <% if project.budget_status < 75 %>
            <span class="ion ion-alert-circled right" style='color:red'> <small>Behind Budget <%= 100 - project.budget_status %>%</small></span>
          <% elsif project.budget_status < 95 %>
            <span class="ion ion-alert-circled right" style='color:orange'> <small>Behind Budget <%= 100 - project.budget_status %>%</small></span>
          <% else %>
            <span class="ion ion-checkmark-circled right" style='color:green'></span>
          <% end %>
        </div>
        <div class="panel-body">
          <div id="map<%= project.id %>" style="height: 300px"></div>
        </div>
      </div>
    </div>
    <script>
      $(document).ready(function() {
        google.maps.event.addDomListener(window, 'load', function() {
          var map<%= project.id %> = new google.maps.Map(document.getElementById("map<%= project.id %>"), {
            zoom: 13,
            center: new google.maps.LatLng(<%= project.lat %>, <%= project.lng %>),
            mapTypeId: google.maps.MapTypeId.SATELLITE,
            disableDefaultUI: true,
            zoomControl: true,
            scrollwheel: false
          });

          google.maps.event.addListener(map<%= project.id %>, 'click', function(event){
            this.setOptions({scrollwheel:true});
          });
        });
      });
    </script>
  <% end %>
</div>

<!-- row -->
<div class="row">

  <!-- Analytics -->
  <!-- Project stats -->
  <div class="col-md-7">
    <div class="panel panel-default mb20 panel-hovered project-stats table-responsive">
      <div class="panel-heading">Active Headings Nearing Completion</div>
      <div class="panel-body">
        <table class="table">
          <thead>
            <tr>
              <th class="col-sm-5">Project</th>
              <th class="col-sm-5">Heading</th>
              <th class="col-sm-1">Progress</th>
            </tr>
          </thead>
          <tbody>

            <% Heading.where('completion > 80 AND status = ?', 'Available').order('completion DESC').each do |heading| %>
              <tr>
                <td><%= heading.project.name %></td>
                <td><%= heading.name %></td>
                <td class="text-center">
                  <span class="sparkline" data-Type="pie" data-SliceColors="[#4CAF50,#eee]" data-Width="2em" data-Height="2em"><%= heading.completion %>,<%= 100 - heading.completion %></span>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <%= render '/common/activities', activities:
    [
      { type: 'success', time: '1 hour ago',  message: 'Broadmeadow Heading 2 Available Again' },
      { type: 'primary', time: '2 hours ago', message: 'Broadmeadow Heading 12 Daily Report Submitted' },
      { type: 'warning', time: '3 hours ago', message: 'Blackwater Heading 7 changed status to Unavailable - No Vent / High Radiation' },
      { type: 'info',    time: '4 hours ago', message: 'Mount Arthur Heading 11 is available but unused for 12 days' },
      { type: 'warning', time: '4 hours ago', message: 'Broadmeadow Heading 2 changed status to Unavailable - Unplanned MOP Interaction' },
    ] %>
  <!-- #end recent activities -->

</div> <!-- #end row -->

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>